
// Simulated data for agents to return
// In a real application, these would be generated by actual LLM calls and API integrations

export const simulations = {
  marketTrends: {
    trends: [
      { trend: "Video content", growth: 32, confidence: 0.89 },
      { trend: "AI-personalization", growth: 47, confidence: 0.92 },
      { trend: "Voice search", growth: 28, confidence: 0.76 },
      { trend: "Sustainability messaging", growth: 21, confidence: 0.82 }
    ],
    insights: [
      "Video content continues to dominate engagement metrics across platforms",
      "AI-driven personalization is showing strongest ROI growth quarter-over-quarter",
      "Voice search optimization becoming critical for discovery",
      "Sustainability messaging resonates strongly with 25-34 demographic"
    ],
    recommendations: [
      "Increase video content production by 30% in Q3",
      "Implement AI personalization in email campaigns",
      "Optimize product descriptions for voice search patterns",
      "Integrate sustainability messaging into brand campaigns"
    ],
    marketShare: {
      company: 23,
      competitor1: 27,
      competitor2: 18,
      competitor3: 14,
      others: 18
    },
    sentiment: {
      positive: 62,
      neutral: 28,
      negative: 10
    }
  },
  
  customerSegmentation: {
    segments: [
      { 
        name: "High-Value Loyalists", 
        percentage: 18, 
        characteristics: ["Repeat purchases", "High AOV", "Long retention"],
        channels: ["Email", "Direct", "Loyalty program"],
        growth: 7
      },
      { 
        name: "Price-Sensitive Occasionals", 
        percentage: 32, 
        characteristics: ["Sale-driven", "Seasonal", "Multiple platforms"],
        channels: ["Social media", "Search", "Deal sites"],
        growth: 12
      },
      { 
        name: "New Explorers", 
        percentage: 24, 
        characteristics: ["First-time buyers", "Research-focused", "Brand comparing"],
        channels: ["Content marketing", "Search", "Reviews"],
        growth: 18
      },
      { 
        name: "Dormant Potentials", 
        percentage: 26, 
        characteristics: ["Past customers", "Low engagement", "Brand aware"],
        channels: ["Retargeting", "Email", "Special offers"],
        growth: -5
      }
    ],
    insights: [
      "High-Value Loyalists generate 43% of total revenue despite being only 18% of customer base",
      "Price-Sensitive segment growing fastest at 12% YoY",
      "New Explorers have highest social sharing rate at 28%",
      "Dormant Potentials respond well to personalized win-back campaigns (+32% conversion)"
    ],
    recommendations: [
      "Develop tiered rewards program for High-Value Loyalists",
      "Create flash sales for Price-Sensitive segment to increase purchase frequency",
      "Expand content marketing to capture more New Explorers",
      "Launch targeted win-back campaign for Dormant Potentials"
    ]
  },
  
  campaignPerformance: {
    recentCampaigns: [
      {
        name: "Summer Collection Launch",
        performance: 92,
        roi: 3.7,
        engagement: 23500,
        conversion: 4.2,
        insight: "Video content outperformed static images by 3.8x"
      },
      {
        name: "Customer Loyalty Program",
        performance: 88,
        roi: 5.2,
        engagement: 18700,
        conversion: 7.6,
        insight: "Tiered rewards drove 32% higher participation"
      },
      {
        name: "Holiday Flash Sale",
        performance: 76,
        roi: 2.9,
        engagement: 42100,
        conversion: 3.5,
        insight: "Email campaigns had 2.4x better conversion than social"
      }
    ],
    channelEffectiveness: [
      { channel: "Email", effectiveness: 87, costEfficiency: 91, trending: "up" },
      { channel: "Social Media", effectiveness: 82, costEfficiency: 74, trending: "up" },
      { channel: "Search", effectiveness: 78, costEfficiency: 82, trending: "stable" },
      { channel: "Display", effectiveness: 65, costEfficiency: 58, trending: "down" },
      { channel: "Content", effectiveness: 74, costEfficiency: 85, trending: "up" }
    ],
    recommendations: [
      "Increase email marketing budget by 15%",
      "Shift 10% of display budget to social media",
      "A/B test video vs. static content across channels",
      "Implement sequential retargeting across channels"
    ]
  },
  
  roiAnalysis: {
    channelROI: [
      { channel: "Email", roi: 4.3, changePct: 7.5 },
      { channel: "Paid Social", roi: 2.8, changePct: 12.0 },
      { channel: "Organic Social", roi: 3.5, changePct: 5.2 },
      { channel: "SEO", roi: 5.1, changePct: 3.8 },
      { channel: "SEM", roi: 3.2, changePct: -2.1 },
      { channel: "Display", roi: 1.7, changePct: -8.3 },
      { channel: "Affiliate", roi: 3.9, changePct: 6.7 }
    ],
    campaignEfficiency: {
      topPerforming: ["Email Newsletter Series", "Influencer Partnership", "Loyalty Program"],
      underPerforming: ["Banner Display Ads", "Print Campaign", "Radio Spots"],
      opportunities: ["Video Tutorials", "Customer Testimonials", "Interactive Content"]
    },
    budgetOptimization: {
      recommendations: [
        "Increase email marketing allocation by 20%",
        "Reduce display ad spending by 15%",
        "Reallocate 10% of budget from radio to podcast sponsorships",
        "Double investment in SEO and content marketing"
      ],
      projectedImpact: {
        currentROI: 2.7,
        optimizedROI: 3.4,
        additionalRevenue: "$580,000"
      }
    }
  }
};
