// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzkdyqcigyvozzqibvkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16a2R5cWNpZ3l2b3p6cWlidmtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDk1ODgsImV4cCI6MjA1OTYyNTU4OH0.j07kZuL6A4A5alAQDDSRNZI9kBMeJNvMjT3u4xB_I5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);